services:
  vault:
    image: vault:1.13.3
    container_name: VaultEventHub
    hostname: vault
    ports:
      - 8200:8200
    volumes:
      - ./config.hcl:/vault/config/config.hcl
      - vault-data:/vault/file/
    environment:
      - VAULT_ADDR=http://127.0.0.1:8200
    cap_add:
      - IPC_LOCK
    command: server
    restart: always
    networks:
      - ServiceNetwork

  vault-init:
    image: vault:1.13.3
    container_name: VaultEventHub-Init
    environment:
      - VAULT_ADDR=http://vault:8200
      - MY_VAULT_TOKEN=${MY_VAULT_TOKEN:-test}
    volumes:
      - ./vault-root-token:/vault/file/vault-root-token
      - ./vault-init.sh:/usr/local/bin/vault-init.sh
      - vault-data:/vault/file/
    command: /usr/local/bin/vault-init.sh
    restart: no
    networks:
      - ServiceNetwork
    depends_on:
      - vault

networks:
  ServiceNetwork:
    external: true
    driver: bridge

volumes:
  vault-data:
